### ISSUE TITLE
Add minimal benchmark example

### ISSUE THREAD

**Issue by 5ei74R0** [5ei74R0/llm_playground#2]
# Roadmap
- [ ] Write a code to evaluate LLaMA 7B on SST2.
- [ ] Write a code to fine-tune LLaMA 7B w/ LoRA on SST2.
- [ ] Write a code to fine-tune LLaMA 7B w/ LoRA & evaluate it on MNLI.
- [ ] Add another model
- [ ] Add other 3 or more benchmark datasets.

**Comment by 5ei74R0** [comment]
### Authors of T5 converted STS-B to text-to-text format to train.
https://dl.acm.org/doi/pdf/10.5555/3455716.3455856
> We were able to straightforwardly cast all of the tasks we considered into a text-to-text format with the exception of __STS-B, which is a regression task where the goal is to predict a similarity score between 1 and 5__. We found that most of these scores were annotated in increments of 0.2, so __we simply rounded any score to the nearest increment of 0.2 and converted the result to a literal string representation of the number__ (e.g. the floating-point value 2.57 would be mapped to the string “2.6”). __At test time, if the model outputs a string corresponding to a number between 1 and 5, we convert it to a floating-point value; otherwise, we treat the model’s prediction as incorrect__. This effectively recasts the STS-B regression problem as a 21-class classification problem.

#### preprocess
https://github.com/google-research/text-to-text-transfer-transformer/blob/e0a69cd19d4e8b37332a0579715bbddb6e5e0830/t5/data/glue_utils.py#L93-L95
```python
  # stsb uses a floating point target, so use special preprocessor
  if builder_config.name == "stsb":
    return preprocessors.stsb
```

https://github.com/google-research/text-to-text-transfer-transformer/blob/e0a69cd19d4e8b37332a0579715bbddb6e5e0830/t5/data/preprocessors.py#L816-L855
```python
  strs_to_join = [
      'stsb sentence1:', x['sentence1'], 'sentence2:', x['sentence2']
  ]
  label_string = tf.as_string(tf.round(x['label'] * 5) / 5, precision=1)
  joined = tf.strings.join(strs_to_join, separator=' ')
  return {'inputs': joined, 'targets': label_string, 'idx': x['idx']}
```

#### postprocess (`str->float`)
https://github.com/google-research/text-to-text-transfer-transformer/blob/e0a69cd19d4e8b37332a0579715bbddb6e5e0830/t5/data/glue_utils.py#L125-L127
```python
def get_glue_postprocess_fn(builder_config):
  if builder_config.name == "stsb":
    return postprocessors.string_to_float
```

https://github.com/google-research/text-to-text-transfer-transformer/blob/e0a69cd19d4e8b37332a0579715bbddb6e5e0830/t5/data/postprocessors.py#L28-L33
```python
def string_to_float(string, default=-1., **unused_kwargs):
  """Converts string to float, using default when conversion not possible."""
  try:
    return float(string)
  except ValueError:
    return default
```
- If parsing fails, they convert it to -1.

#### Metric (`scipy.stats.spearmanr`)
https://github.com/google-research/text-to-text-transfer-transformer/blob/e0a69cd19d4e8b37332a0579715bbddb6e5e0830/t5/data/glue_utils.py#L143
```python
("stsb", [metrics.pearson_corrcoef, metrics.spearman_corrcoef]),
```

https://github.com/google-research/text-to-text-transfer-transformer/blob/e0a69cd19d4e8b37332a0579715bbddb6e5e0830/t5/evaluation/metrics.py#L220-L223
```python
def spearman_corrcoef(targets, predictions):
  """Spearman correlation coefficient."""
  return {"spearman_corrcoef":
              100 * scipy.stats.spearmanr(targets, predictions)[0]}
```

**Comment by 5ei74R0** [comment]
### Two ways
#### (i) fully follow their approach
 (LLaMA uses LM as their objective)
#### (ii) partially follow their approach
Convert STS-B to classification task and fine-tune to solve classification
